# Site settings
author: Jared epps 
title: Why did you decide to study Software Engineering?
header-img: img/home-bg.png
email: jared.epps322@gmail.com
copyright_name: Jared epps 
description: > # this means to ignore newlines until "baseurl:"
  Software Engineering
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  geno1957

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
